### ISSUE TITLE
Change name to "Awesome OS4OS" ?

### ISSUE THREAD

**Issue by nokome** [os4os/Awesome-OS4OS#1]
How about changing the name of the repo to "Awesome OS4OS". A bit more fun and in the spirit of other "awesome lists" : https://github.com/sindresorhus/awesome. 

But mostly because then we could get some cool sunglasses ! 

[![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

**Comment by daniellecrobinson** [comment]
DOING IT! Good idea @nokome
